[config]
type = "pipeline"
chartbook_format_version = "0.0.2"

[site]
title = "p14_us_treasury_yield_curve_construction_and_model_comparison"
author = "Phoebe Fingold, Annie Reynolds"
copyright = "2025"
logo_path = ""
favicon_path = ""

[pipeline]
id = "P1"
pipeline_name = "p14_us_treasury_yield_curve_construction_and_model_comparison"
pipeline_description = "This project studies how the U.S. Treasury yield curve is constructed and how different modeling choices affect its shape and interpretation."
lead_pipeline_developer = "Phoebe Fingold, Annie Reynolds"
contributors = ["Phoebe Fingold, Annie Reynolds"]
software_modules_command = "module load anaconda3/3.11.4 TeXLive/2023"
runs_on_grid_or_windows_or_other = "Windows/Linux/MacOS"
git_repo_URL = ""
README_file_path = "./README.md"

[notebooks]


[notebooks.01_example_notebook_interactive]
notebook_name = "Example Notebook Interactive"
notebook_description = "Example notebook for demonstrating how to construct a Chartbook notebook."
notebook_path = "_output/01_example_notebook_interactive.ipynb"




[dataframes]


[charts]

